site_name: "medium-articles (kamrankhalid06)"
site_description: "Teaching examples and runnable code for Medium articles"
nav:
  - Home: index.md
  - Articles:
      - "Intro": articles/01-intro-to-topic.md
theme:
  name: material
docs_dir: docs
